WebDevStudios/constant-contact-forms

assets/css/admin-style.css
assets/sass/_admin-pages.scss
includes/class-settings.php

Main options page: [https://[env]/wp-admin/edit.php?post_type=ctct_forms&page=ctct_options_settings_general](https://[env]/wp-admin/edit.php?post_type=ctct_forms&page=ctct_options_settings_general)
This update breaks the CtCt Forms Settings options page into separate tabs, using CMB2. All options are still saved to a single option key, `ctct_options_settings`.
1. Use the link above (modify domain for the current environment) or navigate to wp-admin > Contact Form > Settings.
2. Navigate to each section by clicking its tab.
3. Change settings, save, and confirm settings are retained after load.

CC-12: Separate out options page into tabs

---

includes/class-notification-content.php
includes/class-notifications.php
includes/class-uninstall.php
includes/helper-functions.php

[CC-43](https://webdevstudios.atlassian.net/browse/CC-43)
- Upon form deletion: add all references to form in both posts (all post types with status "publish") and widgets (Constant Contact Form and Text widgets) to new `ctct_deleted_forms` option.
- Upon form restore: remove all references to restored form from `ctct_deleted_forms` option.
- On admin page load: if any deleted form references exist in `ctct_deleted_forms` option, display dismissible notice with links to each reference for each form.
- Upon dismissing notice: remove `ctct_deleted_forms` option.
- Create a form and place a shortcode in a post or widget, or add a CC form widget with a reference to that form.
- Delete form and confirm notice appears listing references.
- Restore form and confirm notice disappears.
- Repeat …

CC-43: Notify site owners of existing shortcode embeds for forms that get deleted

---

includes/class-api.php
includes/class-display.php
readme.txt

[CC-29](https://webdevstudios.atlassian.net/browse/CC-29)
---
Adds the form ID and field ID as third and fourth parameters to the `constant_contact_input_classes` filter.

CC-29: Add Field ID to input_classes Filter

---

includes/class-recaptcha-v2.php

Update reCAPTCHA v2 inline js dependency.
[CC-116](https://webdevstudios.atlassian.net/browse/CC-116)

CC-116: reCAPTCHA inline JS broken if jquery is dequeued/unregistered by site

---

CHANGELOG.md
constant-contact-forms.php
includes/class-logging.php
includes/class-settings.php
includes/class-uninstall.php

Ticket: [CC-128](https://webdevstudios.atlassian.net/browse/CC-128)
- Changes logging directory from `wp-content/ctct-logs` to `wp-content/uploads/ctct-logs`
- Removes old logging directory and files for versions <= 1.8.1.
- Removes new logging directory and files on uninstall.
- (For local testing until we bump the actual plugin version) Change `constant-contact-forms.php` line 75 to be any higher version than 1.8.1.
- Ensure logging is enabled (Contact Form > Settings > Support > Enable logging...).
- Check local files to confirm old logging dir was removed and new dir was created.
- Uninstall plugin via admin to confirm new logging dir was removed (I tested on my local and it worked).

CC-128: Change logging location

---

package-lock.json
package.json

Ticket: [CC-132](https://webdevstudios.atlassian.net/browse/CC-132)
Ran `npm update` to update main packages.
Ran `npm audit fix` to address "low" vulnerabilities.
Note: There are some "moderate" and "high" vulnerabilities related to `gulp-cssnano`, a deprecated package replaced by `cssnano`. Fixing this will be addressed in another ticket.

CC-132: Update npm dependencies

---

gulpfile.js
package-lock.json
package.json

Ticket: [CC-133](https://webdevstudios.atlassian.net/browse/CC-133)
Uninstalled deprecated dev dependency `gulp-cssnano`.
Installed dev dependency `cssnano`.
Updated build process to use new package settings.
Please test locally by editing a .scss file and ensuring the build process completes without errors. (`npm install` then `npm run watch`)

CSS-133: Replace gulp-cssnano with cssnano

---

includes/class-display-shortcode.php
includes/class-display.php
includes/class-process-form.php

Ticket: [CC-143](https://webdevstudios.atlassian.net/browse/CC-143)
Adds hidden `ctct-instance` field to all forms. This is the unique index of the instance of the `ConstantContact_Display_Shortcode` class.
On submission, the `$_POST['ctct-instance']` field is checked against the current, passed `$instance` value and form processing aborts if these do not match.
1. Add multiple instances of a single form on one page (I tested using both the shortcode and the Gutenberg block).
2. Ensure Google reCAPTCHA v2 is enabled.
3. Validate and submit one form.
4. Ensure the success message appears in place of the correct form (e.g., if the third form on the page was submitted, that form should display the success message instead of the success message defaulting to the first instance of the form). …

CC-143: Address issues with multiple form copies on single page

---

constant-contact-forms.php
includes/class-recaptcha-v2.php
readme.txt

PHP5.6 doesn't have type hints available like we tried to use in one spot.

Hotfix php56 compat

---

constant-contact-forms.php
includes/class-logging.php
includes/class-settings.php
includes/helper-functions.php

[CC-158](https://webdevstudios.atlassian.net/browse/CC-158)
In addition to using `wp_mkdir_p()` to create the logging directory, I also resolved an issue that I repeatedly saw in local testing where the logging admin page would say no log file had been created, when the file had indeed been created. Also simplified some of the error message logic on the logging admin page, and read the log file from the filesystem instead of remotely.
Use wp_mkdir_p to create log directory
Add a single method for logging initialization
Fix my typo
Initialize logging on init hook
Replace call to instance of self with $this
Use initialize_logging method
Prefer wp_safe_redirect
Simplify error messaging in admin_page_display

CC-158 use wp_mkdir_p and other debug log improvements

---

includes/class-mail.php
includes/class-process-form.php

Ticket: [CC-39](https://webdevstudios.atlassian.net/browse/CC-39)
Forces email notification if request to add/update contact via CC API fails.
- Email mirrors a regular (non-forced) email notification on contact addition/update, with the added error message, "An error occurred while attempting Constant Contact API request."
1. Check "Disable E-mail Notifications" under Contact Form > Settings.
2. Ensure the site is connected to a CC account.
3. Add a form to the site and select a list for the form.
4. Update `includes/class-api.php` line 547 to return false (to imitate a failed API request).
5. Attempt to submit the form on the frontend.
6. Check for email notification (via email logging plugin if local doesn't send emails) and confirm:
- Email contains all data from form
- Email contains …

CC-39: Force email notification on API request failure

---

CHANGELOG.md
constant-contact-forms.php
includes/class-logging.php
includes/class-notification-content.php
includes/class-notifications.php
includes/class-settings.php
includes/class-uninstall.php
includes/helper-functions.php
package.json
readme.txt

Looks like we had some leftover "@since NEXT" from previous releases. Matched their actual version number up against WPORG SVN tags.
Update stable tag and changelog version to 1.8.5
Remove "Replaced usage of non-unique IDs on frontend form elements" from 1.8.5 changelog in readme
Update version to 1.8.5 in package.json
Update plugin bootstrap header version field and constant to 1.8.5
Add 1.8.5 changes from readme.txt to CHANGELOG.md
Update @since NEXT for items that were previously released in 1.8.0
Update @since NEXT for items that were previously released in 1.8.2
Update @since NEXT for 1.8.5

Chore/prep release 1.8.5

---

includes/class-cpts.php
includes/class-display-shortcode.php
includes/class-display.php
includes/class-gutenberg.php
includes/class-logging.php
includes/class-middleware.php
includes/class-process-form.php
includes/class-settings.php
includes/compatibility.php
includes/helper-functions.php
includes/widgets/contact-form-select.php

Ticket: [CC-179](https://webdevstudios.atlassian.net/browse/CC-179)
Resolves `WordPress.Security.*` linting errors, explicitly mutes, or fixes ignore/disable comments.
```
PHP CODE SNIFFER VIOLATION SOURCE SUMMARY
--------------------------------------------------------------------------------
SOURCE                                                                     COUNT
--------------------------------------------------------------------------------
WordPress.Security.NonceVerification.Recommended                           12
WordPress.Security.NonceVerification.Missing                               9
WordPress.Security.EscapeOutput.DeprecatedWhitelistCommentFound            5
WordPress.Security.EscapeOutput.OutputNotEscaped                           1 …
```

CC-179: Fix security linting errors

---

includes/class-recaptcha-v2.php
includes/class-recaptcha-v3.php
includes/class-recaptcha.php
phpcs.xml.dist

Ticket: [CC-180](https://webdevstudios.atlassian.net/browse/CC-180)
Per concerns around changing class and file names at this time, we're leaving them as-is and explicitly muting warnings.
```
PHP CODE SNIFFER VIOLATION SOURCE SUMMARY
--------------------------------------------------------------------------------
SOURCE                                                                     COUNT
--------------------------------------------------------------------------------
WordPress.Files.FileName.InvalidClassFileName                              29
PEAR.NamingConventions.ValidClassName.Invalid                              3
```

CC-180: Mute class/file name warnings

---

includes/class-process-form.php

Ticket: [CC-181](https://webdevstudios.atlassian.net/browse/CC-181)
Mutes warnings about `serialize()` as current use is just as a step to create a key hash.
Swaps `parse_url()` for `wp_parse_url()`.
Eliminates the following warnings:
```
PHP CODE SNIFFER VIOLATION SOURCE SUMMARY
--------------------------------------------------------------------------------
SOURCE                                                                     COUNT
--------------------------------------------------------------------------------
WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize                  17
WordPress.WP.AlternativeFunctions.parse_url_parse_url                      1
```

CC-181: Address function warnings

---

constant-contact-forms.php
includes/class-check.php

Ticket: [CC-177](https://webdevstudios.atlassian.net/browse/CC-177)
Removes old `ISSSL` constant and related block, as this is no longer used by the current vendor files.
Mutes phpcs warnings around usage of WP Core cron filters.

CC-177: Address remaining prefix warnings

---

CHANGELOG.md
constant-contact-forms.php
includes/class-api.php
includes/class-process-form.php
readme.txt

A bugfix release, [1.8.6](https://github.com/WebDevStudios/constant-contact-forms/releases/tag/1.8.6), was merged into and tagged on master, from sprint/20.07 in PR #492, but the sprint/20.06-2 code hadn't yet shipped.
This PR updates sprint/20.06-2 with those changes from master in prep for release.

Update sprint/20.06-2 with changes from master

---

constant-contact-forms.php
includes/class-api.php
includes/class-display.php
includes/class-lists.php
includes/class-logging.php
includes/class-mail.php
includes/class-process-form.php
includes/class-recaptcha.php
includes/class-settings.php
includes/class-uninstall.php
includes/class-user-customizations.php
includes/deprecated.php
includes/helper-functions.php

Ticket: [CC-178](https://webdevstudios.atlassian.net/browse/CC-178)
Deprecates functions and hooks with incorrect plugin prefix (`ctct_`), replacing with `constant_contact_` variations.
- Deprecates filters and actions with old prefix via `apply_filters_deprecated()` and `do_action_deprecated()`, respectively, and creates new, properly-prefixed filters and actions.
- Deprecates functions with old prefix:
- Moves the original functions to a new `deprecated.php` file.
- Calls `_deprecated_function()` within old functions to indicate improper usage.
- Creates new functions with proper prefix in original functions' locations.
- Calls new functions from old functions to preserve original functionality.
- Updates calls to old functions to properly reference new functions.
1. Confirm CC admin …

CC-178: Fix Prefix Mixmatches

---

includes/class-mail.php

Ticket: [CC-183](https://webdevstudios.atlassian.net/browse/CC-183)
Removes `\` within placeholder in `sprintf`, which was causing part of the placeholder to display to the end user.
The quickest way to force this to display in an admin email is the following:
1. Ensure the CC Forms setting "Disable E-mail Notifications" is _unchecked_.
2. At the top of the function body for `maybe_append_forced_email_notice_note()` (`includes/class-mail.php`), set `$was_forced = true` to force this message for all emails.
3. Process a form submission, and the corresponding admin email should include the "forced email" note as shown above.

CC-183: Fix sprintf placeholders

---

includes/class-display.php

Recent forum support spam showed first/last name fields exceeding 50characters and thus API rejection with appropriate errors. This adds maxlength for those fields, when used.

limit first and last name fields to 50char as dictated by the APIv2 docs

---

includes/class-display.php
includes/class-process-form.php

Ticket: [CC-195](https://webdevstudios.atlassian.net/browse/CC-195)
**Description**
Fixes authenticate user exploit in Add New Form controls by escaping (`esc_html`) the output.
**Steps to Verify**
Follow step #3 in the [original ticket](https://webdevstudios.atlassian.net/browse/CC-195)

Escaping HTML output on button label, button placeholder and success message

---

includes/class-display.php
includes/class-process-form.php

Ticket: [CC-196](https://webdevstudios.atlassian.net/browse/CC-196)
Fixes list selection process (per CC-36):
- List selection field should only appear when CC account is connected; check/error messages related to this field should likewise only appear if CC account is connected.
1. With no CC account connected, confirm form(s) submit with no error messages relating to list selection.
2. Check email or use mail logging to confirm form was submitted successfully.
3. With CC account connected, add multiple list options to a form.
4. On frontend, confirm list selection error message displays if no lists selected.
5. Confirm form submits with no error message if at least one list is selected.
6. Log into Constant Contact account and confirm a) submissions were successful, and b) contact was …

CC-196: Allow users to choose list -- Fix for non-connected CC accounts

---

includes/class-builder-fields.php

https://webdevstudios.atlassian.net/browse/CC-203
The user reports confusion when first creating a form that they didn't know a list needed to be selected. Added messaging to remind users to select at least one. Additionally in the event, no list exists a help links to the list creation page.
No Lists Exist
List Do Exist

CC-203 Additional tooltips

---

constant-contact-forms.php
includes/class-elementor.php
includes/widgets/elementor-widget.php

Adds a dedicated Elementor Widget.
To validate.
1. Install the base version of the Elementor plugin.
2. Attempt to add a constant contact form widget. (Support for toggling the form title).

CC-200 Elementor Widget

---

constant-contact-forms.php
includes/class-settings.php

**Closes:** https://webdevstudios.atlassian.net/browse/CC-219
Adds Global CSS option to disable frontend CSS all together. When enabled frontend styles will not load.

CSC-219 Disables Adds option to disable frontend css.

---

readme.txt

Updated text to better represent the role of the product. Removed wording that the plugin can be used w/o Constant Contact account to move future development efforts. Added new how to get started section to make a clear setup process. Added missing contributors. Updated FAQ links to show their article name instead of a direct link.

CC-220 Updated repo marketing page.

---

includes/class-mail.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-197
Description: Even connected and emails disabled if a list is created without a list selected we should force an email to be sent to site owner to prevent loosing entries.

Force email on no list logic.

---

includes/class-display.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-226 change the surrounding script to small. Testing on multiple themes showed design looks good. Note: if a user has explicitly targeted using `sub` as a selector they'll be forced to make changes.

Legal text change from sub to small.

---

includes/class-display.php
includes/class-settings.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-229
Description: Adds support to override default legal text for opt-in.

Add support to change default legal text.

---

includes/class-display.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-228
Description
Added two filters for user to be ably to override state and zipcode labels.
Example
In `functions.php` file of twentytwenty labels are overrideable
```
function change_state( $state ) {
return 'Province';
}
add_filter( 'constant_contact_address_state', 'change_state' );
function change_zip( $state ) {
return 'Postal Code';
}
add_filter( 'constant_contact_address_zip_code', 'change_zip' );
```
Before
After

Added filters to change State and Zip Code labels.

---

includes/class-display.php

CC-254 Remove erroneous label markup
After I approved and merge #558 I noticed that there was a second <label> element in the 500 character limit notice.
This PR resolves that.
Before:
```
<p class="ctct-form-field">
<span class="ctct-label-top">
<label for="custom_text_area___99a6a1bc9800303822f0b441fd116a95_0">
Custom Text Area 
</label>
</span>
<textarea class="ctct-textarea ctct-label-top" name="custom_text_area___99a6a1bc9800303822f0b441fd116a95"
id="custom_text_area___99a6a1bc9800303822f0b441fd116a95_0" placeholder="" maxlength="500">
</textarea>
<span class="ctct-textarea-warning-label">
<label for="custom_text_area___99a6a1bc9800303822f0b441fd116a95_0">
Limit 500 Characters 
</label>
</span>
</p>
```
After:
```
<p class="ctct-form-field">
<span class="ctct-label-top">
<label …
```

CC-254 Remove erroneous label markup

---

includes/class-settings.php

Ticket: https://webdevstudios.atlassian.net/jira/software/projects/CC/boards/9?selectedIssue=CC-283
Description
Default `get_optin_list_options()` to an empty array instead of astring

CC-283  Have `get_optin_list_options()` options fetch default to empty array

---

includes/class-settings.php

Fixes parse error on the release/1.13.0 branch caused by trailing comma on sprintf.

fixed: Removed traliling commas on sprintf causing errors on lower php versions

---

assets/js/ctct-plugin-frontend/validation.js

When AJAX is enabled on CTCT forms the html5 validation was disabled. 
This was due to the preventDefault necessary to stop the page from refreshing.

Fixed: HTML5 Native validators not working when ajax is enabled.

---

includes/class-process-form.php

We assume we have `$_POST` at all originally, but we technically may not. Thus we're going to return early if we have nothing.
Most everything beyond that SHOULD be checking and still returning early, but just in case something wonky is going on behind the scenes, let's just exit if we have nothing.

make sure we have anything in $_POST before we proceed

---

includes/class-logging.php
includes/class-uninstall.php

See CC-412 in Jira.
This branch creates an `.htaccess` file for our logging folder and Apache based setups.
This branch also appends a random string of characters to the end of the log file, as well as store that suffix as an option so we can consistently read the correct final file name.
Handles https://patchstack.com/database/vulnerability/constant-contact-forms/wordpress-constant-contact-forms-plugin-2-4-2-sensitive-data-exposure-via-log-file-vulnerability?_a_id=431

Harden up details around log files

---

includes/class-api.php

This PR moves the `$address['kind']` assignment outside of the switch statement, to consistently set regardless of which address fields are used.

set the address kind outside of switch statement

---

includes/class-mail.php

The metadata now stores ALL of the chosen lists as meta, and not just items checked by the user.

remove reliance on meta data and instead rely on POST data for lists being used.

---

includes/class-mail.php

This PR sets some marketing messaging to admin email notifications of new signups, if they don't have an existing connection already.

only add mmarketing message to email notifications if not connected, indicating already having an account

---

composer.json
constant-contact-forms.php
includes/class-notifications.php
package-lock.json
package.json
readme.txt

This PR addresses missed version bumps in the release branch.
It also removes a `src` folder as part of our build collection process, and a php notice prevention.

Release280 two

---

includes/class-cpts.php
includes/class-lists.php
includes/class-notification-content.php
includes/class-settings.php

This PR amends how we're handling lists and some list management, depending on the current state of our API access.
1. Removes need to be connected, to register the list post type. This should help ensure associated lists to forms are still available, even if the API isn't at the moment. Site visitors can still successfully submit
2. Conditionally change the "Sync lists" link based on if we need to manually connect and are connected. Non connected and no API connection issues just do not get the link shown.
3. Conditionally amend our new permanent lists admin notification content, based on connected or not. If not connected and no API issues, encourage signing up and/or connecting the user's account. If connected, retain newly merged wording about making use of the sync, and informing …

Constant Contact Lists updates in various connective states.
