WebDevStudios/constant-contact-forms

includes/class-settings.php

CC-12 Separate Options Page into Tabs - Remove PHP 7 Features

---

readme.txt

Let's get this merged into sprint branch, and then merge sprint branch into master for the time being.

touch up the readme changelog for what we have going so far

---

constant-contact-forms.php

[CC-83](https://webdevstudios.atlassian.net/browse/CC-83)
Remove function and associated add_filter line.

CC-83: Remove ctct_shortcode_button_assets_url function

---

includes/class-builder-fields.php

[CC-60](https://webdevstudios.atlassian.net/browse/CC-60)
Add note about invalid field values (e.g., external site or media file), which will cause CtCt functionality to fail.
Include note on recommended field values.

CC-60: Add clarification for Redirect URL accepted values

---

includes/class-api.php
includes/class-middleware.php

Not quite sure why ae67382 is in there, but it's a safe thing to merge in as well, just in case.
It's all logging.

Cc 91 extra logging

---

includes/class-api.php

Long term, could very likely be cleaned up and probably some sort of shared function created for it, however, for now we have this.
It should be pretty consistent, but any discrepancies should absolutely be called out.

Cc 118/error log issues

---

includes/class-process-form.php

Apparently I didn't have my namespacing accurate previously, and it wasn't immediately obvious due to less than adequate testing.

Get a proper namespace in place.

---

package-lock.json

[CC-124](https://webdevstudios.atlassian.net/browse/CC-124)
- Update package-lock.json
Note: no results shown for `npm outdated` on local `sprint/20.02` branch, but it looks like `package-lock.json` itself was outdated compared to `package.json`.

CC-124: NPM Security Alerts

---

includes/helper-functions.php

Ticket: [CC-131](https://webdevstudios.atlassian.net/browse/CC-131)
Checks if logging file exists, if not, creates logging directory, index, and logging files.
1. Make sure logging is enabled.
2. Delete local logging directory (if exists).
3. Perform an action that would normally log to the CTCT log file (e.g., enable ReCAPTCHA for a form but don't input ReCAPTCHA creds in settings).
4. Confirm logging directory and files are created (should be in `uploads`).
Note: continuing on `sprint/20.02` branch as this builds on updates currently on that branch (but not yet merged to `master`).

CC-131: Add check for existence of logging directory

---

assets/js/ctct-plugin-frontend.js
assets/js/ctct-plugin-recaptcha.js
languages/constant-contact-forms.pot
package-lock.json
package.json

Ticket: [CC-134](https://webdevstudios.atlassian.net/browse/CC-134)
Adds `@wordpress/api-fetch` as dev dependency to avoid build errors (package is referenced in `/assets/js/ctct-plugin-gutenberg/components/single-form-select.js`).

CC-134: Fix npm build errors

---

includes/class-api.php

We forgot to force enable for half the exceptions.

Enable logging for more caught exceptions

---

readme.txt

[CC-151](https://webdevstudios.atlassian.net/browse/CC-151)
Cherry picked the relevant documentation commit from stale PR #467

CC-151 add FAQ item for connection debugging knowledge purposes

---

includes/class-notification-content.php

[CC-153](https://webdevstudios.atlassian.net/browse/CC-153)
Updates error messaging to reference Support tab within settings area.

CC-153: Update error message to reference tab

---

readme.txt

Updates changelog to reflect `sprint/20.06` changes.

CC-164: Changelog updates

---

includes/class-builder-fields.php
includes/class-cpts.php
includes/class-notification-content.php
includes/class-settings.php

Ticket: [CC-173](https://webdevstudios.atlassian.net/browse/CC-173)
Addressed i18n-related linting errors as outlined in ticket.

CC-173: Address i18n linting errors

---

constant-contact-forms.php
includes/class-admin.php
includes/class-api.php
includes/class-connect.php
includes/class-display.php
includes/class-lists.php
includes/class-logging.php
includes/class-mail.php
includes/class-middleware.php
includes/class-notification-content.php
includes/class-notifications.php
includes/class-process-form.php
includes/class-recaptcha-v2.php
includes/class-settings.php
includes/class-shortcode.php
includes/class-uninstall.php
includes/helper-functions.php

Ticket: [CC-175](https://webdevstudios.atlassian.net/browse/CC-175)
Resolves (or explicitly mutes) the following linting errors:
```
PHP CODE SNIFFER VIOLATION SOURCE SUMMARY
-----------------------------------------------------------------------------------
SOURCE                                                                    COUNT
-----------------------------------------------------------------------------------
[x] Generic.Formatting.MultipleStatementAlignment.NotSameWarning              37
[ ] WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound     15
[ ] WebDevStudios.All.RequireAuthor.815dee87b802924681c29bc8a2de5f5271299785  12
[ ] Squiz.Commenting.FunctionComment.EmptyThrows                              11
[ ] Squiz.Commenting.InlineComment.InvalidEndChar …
```

CC-175: Address misc linting errors

---

CHANGELOG.md
constant-contact-forms.php
package.json
readme.txt

Bump version number to 1.8.7
Add 1.8.7 notes to Changelog(s)

Chore/prep release 1.8.7

---

includes/class-display.php

Ticket: [CC-187](https://webdevstudios.atlassian.net/browse/CC-187)
Creates new display method for simplified hidden input rendering.
Removes extraneous hidden type check in standard input method.
Updates display of hidden input fields to use new method.
1. Check frontend display of form and confirm a) hidden inputs (w/ name and value) display as expected, and b) fields are simplified, with necessary attributes only and no extraneous wrapper or label elements.

CC-187: Abstract hidden fields

---

CHANGELOG.md
constant-contact-forms.php
package.json
readme.txt

Update version numbers to 1.8.8

---

includes/class-connect.php

Closes https://webdevstudios.atlassian.net/browse/CC-201

add a try/catch block around this account fetching

---

includes/class-notification-content.php

Closes: https://webdevstudios.atlassian.net/browse/CC-210
Updated support link.

Updated support link.

---

constant-contact-forms.php
package.json
readme.txt

Updated changelog and version numbers.

Prep release of 1.9.1

---

includes/class-connect.php
includes/class-settings.php

Closes https://webdevstudios.atlassian.net/browse/CC-213

Minor patch of depricated functions.

---

.github/workflows/deploy.yml
readme.txt

Updated Github action to prevent composer failure

Chore/prep release 1.11.0 gh actions fix

---

readme.txt

Ticket: https://webdevstudios.atlassian.net/browse/CC-205
Provides additional FAQ to assist users who have a rare issue during plugin updates and lists not being in sync.

Updated FAQ to include upgrade lists from fix.

---

.github/workflows/deploy.yml
includes/cc-modules/form/includes/frontend.php
includes/class-beaver-builder.php
includes/class-display.php
includes/class-elementor.php
includes/class-settings.php
includes/widgets/elementor-widget.php
readme.txt

Chore/prep release 1.11.0 2

---

includes/class-display.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-249
Description: Submit buttons no longer have an empty placeholder attribute.

Buttons no longer have an empty placeholder.

---

includes/class-display.php

https://webdevstudios.atlassian.net/browse/CC-248

Sending all fields for submit button.

---

includes/class-lists.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-260
Description: Resolves typo in nonce_url and adds nonce verification where it previously didn't exist.

Renamed nonce typo and added nonce verification.

---

includes/class-display.php

Ticket: https://webdevstudios.atlassian.net/browse/CC-255

Added class selector to list selector (single) to help with styling.

---

composer.json
composer.lock

Ticket: https://webdevstudios.atlassian.net/browse/CC-264
Description: Update CMB2 to 2.9

Updated CMB2 to 2.9

---

CHANGELOG.md
constant-contact-forms.php
includes/class-builder-fields.php
includes/class-settings.php
package.json
readme.txt

Replace NEXT with 1.12.0
Update version constant and version header to 1.12.0
Update version to 1.12.0 in package.json
Move 1.9.0 – 1.11.0 changes to CHANGELOG.md
Update stable tag in readme to 1.12.0
Add 1.12.0 to changelog remove previous versions

Chore/prep release 1.12.0

---

includes/class-admin-pages.php
includes/class-admin.php
includes/class-builder-fields.php
includes/class-builder.php
includes/class-display.php
includes/class-notification-content.php
includes/class-settings.php

CC-275
Description
- Add `noopener noreferrer` to blank links.
- Refactor multiple translated strings.

CC-275 printf placeholder

---

includes/class-process-form.php

With the added option of disabling 1 minute delay submission there was no error message displayed if the submission failed for some reason. We've added a generic messages that display when api submission fails on the FE and also display the API error itself if the submission catches it. 
Steps to verify: 
1. Make a failing request on the CTCT form on FE. 
2. See the display message 
Fixes : 
https://webdevstudios.atlassian.net/browse/CC-215

Feature/cc-215 Show error message if API fails.

---

assets/js/ctct-plugin-frontend/validation.js

Hiding the form for uniformity when using ajax upon successful submission.

Fixed :: Hiding form after form is successfully submitted.

---

readme.txt

Updated tested upto info to 6.0 RC2

Updated: The tested upto info.

---

package-lock.json

Updated package json lock file.

Updated: Package lock file.

---

includes/widgets/elementor-widget.php

See https://developers.elementor.com/docs/deprecations/simple-example/

Fix deprecated method naming from Elementor

---

includes/compatibility.php

Reverts WebDevStudios/constant-contact-forms#592

Revert "add cleantalk support for their visible fields key that the API does …"

---

includes/class-mail.php
includes/class-process-form.php

Reverts WebDevStudios/constant-contact-forms#614

Revert "Feature/cc 357 use wp constants"

---

CHANGELOG.md
constant-contact-forms.php
includes/class-api.php
package.json
readme.txt

This PR has all the same changes as the previous, but also includes the version bumps and readme.txt changelogs.

Release version 2.4.4.

---

CHANGELOG.md
constant-contact-forms.php
includes/class-api.php
includes/class-process-form.php
package.json
readme.txt

Merge in intended changes for version 2.5.0.
Mostly handles preventing email notifications for failed/spam API requests.

Release250

---

.nvmrc
composer.json
package-lock.json
package.json

This PR handles some updates to our NPM setup and upgrades various packages.

NPM Upgrades

---

includes/class-settings.php

This PR removes a setting that we no longer use.

remove no longer used setting.

---

includes/class-settings.php

This PR creates a new tab dedicated to the global styles settings and moves them into it.

create new tab and move style settings into it.

---

includes/class-settings.php

This PR adds a new "opt in" tab and moves related settings to it.

new opt-in tab and reorder the fields to put a 1-to-many length lists section last.
